apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: conda
  name: conda
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: conda
status:
  loadBalancer: {}
